apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: informer
  labels:
    app: "informer"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        example: informer
        k8s-app: metrics
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: informer-service-account
      containers:
      - image: pk85/k8s-informer:latest
        imagePullPolicy: Always
        name: informer
        ports:
        - name: metrics-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: informer-metrics
  labels:
    k8s-app: metrics
spec:
  selector:
    app: informer
  ports:
  - name: metrics-port
    port: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: informer-service-account
  labels:
    app: "informer"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: informer-cluster-role
  labels:
    app: "informer"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name:  informer-cluster-role-binding
  labels:
    app: "informer"
subjects:
- kind: ServiceAccount
  name: informer-service-account
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: informer-cluster-role
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: informer-metrics
  labels:
    prometheus: core
    app: "informer"
spec:
  selector:
    matchLabels:
      k8s-app: metrics
  targetLabels:
  - k8s-app
  endpoints:
  - port: metrics-port
    interval: 30s
  namespaceSelector:
    matchNames:
    - default





